"""create initial schema

Revision ID: 87daac44c1ea
Revises: 
Create Date: 2026-07-10 21:02:12.436207

"""
from typing import Sequence, Union

from alembic import op
import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87daac44c1ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('embeddings_gemini',
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('NODE', 'EDGE', name='scripture_entity_type'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('model_version', sa.String(length=30), nullable=True),
    sa.Column('source_text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'model', name='uq_embeddings_gemini_entity_model')
    )
    op.create_index('ix_embeddings_gemini_hnsw', 'embeddings_gemini', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('embeddings_openai',
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('NODE', 'EDGE', name='scripture_entity_type'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('model_version', sa.String(length=30), nullable=True),
    sa.Column('source_text', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', 'model', name='uq_embeddings_openai_entity_model')
    )
    op.create_index('ix_embeddings_openai_hnsw', 'embeddings_openai', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_table('nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('STORY_SLOT', 'BEING', name='node_type'), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('review_status', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'PUBLISHED', name='review_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_nodes_data_gin', 'nodes', ['data'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_nodes_review_status'), 'nodes', ['review_status'], unique=False)
    op.create_index(op.f('ix_nodes_type'), 'nodes', ['type'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('NODE', 'EDGE', name='scripture_entity_type'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'PUBLISHED', name='review_status'), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', 'REVISION_REQUESTED', name='review_decision'), nullable=True),
    sa.Column('reviewer', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reviews_entity', 'reviews', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_table('scripture_refs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('NODE', 'EDGE', name='scripture_entity_type'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('book', sa.String(length=30), nullable=False),
    sa.Column('chapter_start', sa.SmallInteger(), nullable=False),
    sa.Column('verse_start', sa.SmallInteger(), nullable=False),
    sa.Column('chapter_end', sa.SmallInteger(), nullable=True),
    sa.Column('verse_end', sa.SmallInteger(), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chapter_start > 0 AND verse_start > 0', name='ck_scripture_refs_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scripture_refs_book_ch_v', 'scripture_refs', ['book', 'chapter_start', 'verse_start'], unique=False)
    op.create_index('ix_scripture_refs_entity', 'scripture_refs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('review_status', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'PUBLISHED', name='review_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_id != target_id', name='ck_edges_no_self_loop'),
    sa.ForeignKeyConstraint(['source_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edges_relationship_type'), 'edges', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_edges_review_status'), 'edges', ['review_status'], unique=False)
    op.create_index('ix_edges_source_target', 'edges', ['source_id', 'target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_edges_source_target', table_name='edges')
    op.drop_index(op.f('ix_edges_review_status'), table_name='edges')
    op.drop_index(op.f('ix_edges_relationship_type'), table_name='edges')
    op.drop_table('edges')
    op.drop_index('ix_scripture_refs_entity', table_name='scripture_refs')
    op.drop_index('ix_scripture_refs_book_ch_v', table_name='scripture_refs')
    op.drop_table('scripture_refs')
    op.drop_index('ix_reviews_entity', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index(op.f('ix_nodes_type'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_review_status'), table_name='nodes')
    op.drop_index('ix_nodes_data_gin', table_name='nodes', postgresql_using='gin')
    op.drop_table('nodes')
    op.drop_index('ix_embeddings_openai_hnsw', table_name='embeddings_openai', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('embeddings_openai')
    op.drop_index('ix_embeddings_gemini_hnsw', table_name='embeddings_gemini', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('embeddings_gemini')
    # ### end Alembic commands ###
